### ISSUE TITLE
Not really an issue...

### ISSUE THREAD

**Issue by Ondry4K** [8none1/bj_led#3]
Hey I just wanted to thank you here because I want to control my leds from my pc and after all troubles decided to search up the name of the leds and this came up, although i havent tried it yet and im getting docker ready, wish me luck.

**Comment by 8none1** [comment]
Thanks @Ondry4K - if you're new to home assistant, then you have quite a journey ahead of you. 

If you're familiar with Python then you could use the bytearray byte sequences to control them without all of Home Assistant.

**Comment by Ondry4K** [comment]
hey man, do you have discord? if yes add me = ondry4k im having some problems and need dicussion

**Comment by Ondry4K** [comment]
hey man, my discord is @ondry4k add me pls i need help (kinda)

**Comment by Ondry4K** [comment]
ondry4k (case sensitive)

**Comment by 8none1** [comment]
I'm afraid I don't offer support, only bug reports.
