### ISSUE TITLE
Color resets when on/off

### ISSUE THREAD

**Issue by Zeelia** [8none1/bj_led#4]
Hi!
Thanks for making this custom component!

Whenever I set a color on the LED strip, and then turn it off, it forgets the color and resets to white/blue everytime I turn it on again.
Home Assistant however, remembers the previously set color when turned back on, but the LED strip doesn't follow that color and is white/blue.
Is it possible to patch this behaviour? 

Thanks!

**Comment by 8none1** [comment]
Thanks for your bug report.

I am not able to reproduce this problem here.  Please can you provide steps to recreate it?
